// WARNING: this file was generated automatically by balde-template-gen

#include <balde.h>
#include <glib.h>

static const gchar *balde_template_form_format = "<form method=\"POST\">\n    <label for=\"name\">Name:</label>\n    <input type=\"text\" name=\"name\" />\n    <input type=\"submit\" value=\"Send!\" />\n</form>\n";
extern void balde_template_form(balde_app_t *app, balde_request_t *request, balde_response_t *response);

void
balde_template_form(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    gchar *rv = g_strdup(balde_template_form_format);
    balde_response_append_body(response, rv);
    g_free(rv);
}
