// WARNING: this file was generated automatically by balde-template-gen

#include <balde.h>
#include <glib.h>

static const gchar *balde_template_hello_format = "<h1>Hello, %s!</h1>\n<p>(%%s)</p>\n";
extern void balde_template_hello(balde_app_t *app, balde_request_t *request, balde_response_t *response);

void
balde_template_hello(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    gchar *rv = g_strdup_printf(balde_template_hello_format,
        balde_response_get_tmpl_var(response, "name"));
    balde_response_append_body(response, rv);
    g_free(rv);
}
