// WARNING: this file was generated automatically by balde-template-gen

#include <balde.h>
#include <glib.h>

static const gchar *balde_template_url_for_format = "<html>\n<body>\n    <a href=\"%s\">View Your Profile</a>\n</body>\n</html>\n";
extern void balde_template_url_for(balde_app_t *app, balde_request_t *request, balde_response_t *response);

void
balde_template_url_for(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    gchar *a1 = balde_tmpl_url_for(app, request,
        "profile",
        FALSE,
        "John");
    gchar *rv = g_strdup_printf(balde_template_url_for_format,
        a1);
    balde_response_append_body(response, rv);
    g_free(a1);
    g_free(rv);
}
